# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Domain\Repositories\Customers\CustomerRepositoryInterface:
        class: App\Domain\Repositories\Customers\CustomerRepository

    App\Domain\Services\Customers\CustomerServiceInterface:
        class: App\Domain\Services\Customers\CustomerService

    App\Domain\Repositories\Carts\CartRepositoryInterface:
        class: App\Domain\Repositories\Carts\CartRepository

    App\Domain\Services\Carts\CartServiceInterface:
        class: App\Domain\Services\Carts\CartService

    App\Domain\Services\Notifier\CartNotifierInterface:
        class: App\Domain\Services\Notifier\EmailCartNotifierInterface

    App\Domain\Services\Carts\CartNotifierServiceInterface:
        class: App\Domain\Services\Carts\CartNotifierService
